meters = float(input("enter number of meters for conversion: "))
print(meters,"meters is")
print(meters * 1000,"millimeters")
print(meters * 100,"centimeters")
print(meters / 1000,"kilometers")
print(meters * 39.37,"inches")
print(meters * 3.281,"feet")
print(meters / 1609,"miles")
print(meters * 1.094,"yards")

